#!/usr/bin/env python3
"""Per-exam coverage report. For each exam it (heuristically) detects the
question labels present in the solution PDF text, compares them with the
labels actually cited in data/*.json, and writes COVERAGE.md.

Detection is approximate (regex over the text dump), so treat the numbers as
a coverage *signal*, not ground truth — the 'missed' list shows which exam
question numbers are not yet cited (often because they were merged into a
combined card, belong to a chapter not keyed by number, or were summarized
because they are figure-heavy)."""
import glob, json, re, pathlib, sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

ROOT = pathlib.Path(__file__).resolve().parent.parent
TXT = ROOT.parent / "AK" / "_txt"
EXAMS = {
    "SS20": "SS_2020_Solutions.txt", "SS21": "SS_2021_Solutions.txt",
    "SS22": "SS_2022_Solutions.txt", "SS23": "SS_2023_Solutions.txt",
    "SS24": "SS_2024_Solutions.txt", "SS25": "SS_2025_Solutions.txt",
    "WS21": "WS_2021_Solutions.txt", "WS22": "WS_2022_Solutions.txt",
    "WS23": "WS_2023_Solutions.txt", "WS24": "WS_2024_Solutions.txt",
    "WS26": "WS_2026_Solutions.txt", "Mock": "Mock_Exam _Solutions.txt",
}

def detect_labels(text):
    """Return the set of question labels detected in an exam's text."""
    labels = set()
    # numeric 'X.Y' at line start (e.g. 2.10, 7.3). Skip point annotations
    # like '0.5' / '1.0' (major 0 or minor 0 are not question numbers).
    for m in re.finditer(r"(?m)^\s*(\d+)\.(\d+)(?=[\s)])", text):
        major, minor = m.group(1), m.group(2)
        if major != "0" and minor != "0":
            labels.add(f"{major}.{minor}")
    # letter-subpart exams: track current Problem N, collect 'PN<letter>'
    problem = None
    for line in text.splitlines():
        pm = re.match(r"^Problem\s+(\d+)\b", line)
        if pm:
            problem = pm.group(1)
            continue
        sm = re.match(r"^\s*([a-z])\)", line)
        if sm and problem:
            labels.add(f"P{problem}{sm.group(1)}")
    return labels

def cited_labels():
    """Map exam -> set of cited labels from the data JSON."""
    cited = {e: set() for e in EXAMS}
    for f in glob.glob(str(ROOT / "data" / "ch*.json")):
        if pathlib.Path(f).name == "chapters.json":
            continue
        data = json.loads(pathlib.Path(f).read_text(encoding="utf-8"))
        for kp in data["knowledge_points"]:
            for q in kp["questions"]:
                for s in q["sources"]:
                    m = re.match(r"^(SS\d\d|WS\d\d|Mock)\s+(.+)$", s)
                    if m and m.group(1) in cited:
                        cited[m.group(1)].add(m.group(2))
    return cited

def main():
    cited = cited_labels()
    rows, tot_det, tot_cov = [], 0, 0
    detail = []
    for ex, fn in EXAMS.items():
        p = TXT / fn
        if not p.exists():
            continue
        det = detect_labels(p.read_text(encoding="utf-8", errors="ignore"))
        cov = det & cited[ex]
        missed = sorted(det - cited[ex], key=lambda s: (s[0].isalpha(), s))
        pct = (100 * len(cov) / len(det)) if det else 0
        rows.append((ex, len(det), len(cov), pct))
        tot_det += len(det); tot_cov += len(cov)
        if missed:
            detail.append((ex, missed))

    lines = ["# Coverage report", "",
             "Auto-generated by `tools/coverage_report.py`. 'Detected' = question labels found in the exam-solution text; 'Cited' = labels referenced by at least one card on the site. Detection is heuristic (regex), so a 'missed' item may simply be merged into a combined card or summarized because it is figure-heavy.", "",
             "| Exam | Detected Qs | Cited on site | Coverage |",
             "|------|------------:|--------------:|---------:|"]
    for ex, d, c, pct in rows:
        lines.append(f"| {ex} | {d} | {c} | {pct:.0f}% |")
    overall = (100 * tot_cov / tot_det) if tot_det else 0
    lines.append(f"| **Total** | **{tot_det}** | **{tot_cov}** | **{overall:.0f}%** |")
    lines += ["", "## Not yet cited (per exam)",
              "These exam question numbers are not directly cited yet — many are merged into a combined card, belong to a topic cited under a different number, or were summarized (figure/heavy-info questions).", ""]
    for ex, missed in detail:
        lines.append(f"- **{ex}**: {', '.join(missed)}")
    (ROOT / "COVERAGE.md").write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote COVERAGE.md — overall {tot_cov}/{tot_det} ({overall:.0f}%) of detected labels cited")

if __name__ == "__main__":
    main()
